### ISSUE TITLE
"Better ways to do it" instead of "How it should be"

### ISSUE THREAD

**Issue by scriptype** [bcinarli/frontend-horror#4]
A suggestion.

Changing the title of _good way_ section to something like **"better ways to do it"** or **"solutions"** would promote more contributions.

Some _good_ code samples can be written in different ways, with different approaches, and all those can still be good / acceptable / elegant solutions. If people have ideas on how to accomplish a task in some other elegant way, they can easily just add another solution to the problem, by appending their sample in **"solutions"** section.

**Comment by bcinarli** [comment]
Maybe we can play with wording. According to me "How" keyword is the main indicator. Because, I want to emphasise, "_how_" the proper approach was for the desired code.

"**How it could be?**", "**How could you write it better?**" etc.

**Comment by scriptype** [comment]
What I'm actually suggesting here is changing the  _bad way_ - _good way_ format into something that can more easily accept **more than one solution**. So anyone can suggest a different approach for the solution and there would be more than one solution to problem.

Again, only a suggestion.

**Comment by bcinarli** [comment]
No problem, multiple solutions are possible. There is no restriction for only one solution.

**How could you write it better?**
_Solution 1_

```
// Solution will be here
```

_Solution 2_

```
// Solution will be here
```

**Comment by scriptype** [comment]
Great √
